### ISSUE TITLE
Implement YAML parsing and field extraction for CommandLineTool - Part One

### ISSUE THREAD

**Issue by waleedev01** [waleedev01/analytics_automated_v2#1]
Convert the CWL YAML file that 
- class = CommandLineTool
- contain at lease one input file
- contain at least one output file
- have multiple input parameter

**Comment by Cenxn** [comment]
Implemented the function on commit 6ba85551ce8c6af041f57b64737ab40c922be03a.
Raised new requirement:
- Function to handle the expected `backend` of the task (perhaps from the rest api call)
- Add for cwl file test case to test the function could hanld cwl file with no input and output.
