### ISSUE TITLE
Implement YAML parsing and field extraction for CWL Standard Workflow

### ISSUE THREAD

**Issue by Cenxn** [waleedev01/analytics_automated_v2#10]

**Comment by anisahn09** [comment]
Commits:
- https://github.com/psipred/analytics_automated/commit/94e23fe582849e52219c62375bd3e7e22c8c6b81
- https://github.com/psipred/analytics_automated/commit/44a2afe52c6e1e36e336e1f2a18971f1f52456db
- https://github.com/psipred/analytics_automated/commit/0239d9073d2393fccbd7cbd5b4fcf2989bd9f51f

**Comment by anisahn09** [comment]
closed because it's already merged with the new version
